config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'

  # custom devise routing
  devise_scope :user do
    post '/api/v3/users/sign_in', to: 'sessions#create'
    post '/api/v3/users/sign_up', to: 'registrations#create'
    post '/api/v3/users/oauth', to: 'sessions#oauth'
    post '/api/v3/password_resets', to: 'api/v3/passwords#create'
    put '/api/v3/password_resets', to: 'api/v3/passwords#update'

    post '/api/v3/users/sign_in_with_token', to: 'sessions#sign_in_with_token'
  end

  get '/' => redirect('/admin')

  # /admin/...
  scope '/admin' do
    authenticated :user do
      mount Sidekiq::Web, at: '/sidekiq'
      root to: 'dashboard#index'
    end

    get "/queue-status", to: 'sidekiq_queues#show'

    devise_for :users, controllers: { sessions: 'sessions', registrations: 'registrations' }

    resources :payments, only: :index
    namespace :payments do
      resources :sends, only: :create
      resources :generates, only: %i[new create]
    end
    resources :ad_reports, only: :index
    delete '/payments/:period_start/:period_end/cancel', to: 'payments#destroy', as: :cancel_payments
    resources :payment_recipients

    get '/users/search', to: 'users/search#index', as: :user_search
    resources :users do
      member do
        put :update_subscription
      end
      resources :archivings, only: %i[new create], controller: 'users/archivings'
    end
    post '/users/admin-create', to: 'users#create', as: 'create_user'
    put '/users/:id/admin-update', to: 'users#update', as: 'update_user'

    get '/', to: 'dashboard#index', as: :dashboard
    get '/dashboard/total_sign_ins', to: 'dashboard#total_sign_ins', as: :total_sign_ins
    get 'dashboard/article_clicks', to: 'dashboard#article_clicks', as: :article_clicks
    get 'dashboard/clicks_by_category', to: 'dashboard#clicks_by_category', as: :clicks_by_category
    get 'dashboard/session_duration', to: 'dashboard#session_duration', as: :session_duration

    get 'contents/parent_options', to: 'contents#parent_select_options', as: :parent_select_options
    resources :contents, except: %i[show new create]
    post 'content/removals', to: 'contents/removals#create'
    delete 'content/removals', to: 'contents/removals#destroy'
    post 'content/facebook_scraping', to: 'contents/facebook_scrapings#create'
    resources :campaigns, except: %i[show destroy]
    resources :comments, only: %i[index update destroy]

    resources :images, only: %i[create destroy update]
    resources :organizations, except: [:show] do
      resources :promotions, shallow: true
    end

    resources :locations, except: [:destroy]
    resources :business_locations

    resources :rewrites, except: [:show]

    resources :listservs do
      resources :campaigns, controller: :listserv_campaigns
    end
    resources :subscriptions

    resources :features

    get '/ics/event_instances/:id', to: 'api/v3/event_instances#show', defaults: { format: 'ics' }, as: :event_instances_ics

    get '/sidekiq_wrapper', to: 'sidekiq_wrapper#index'
  end

  # API
  namespace :api do
    namespace :v3, defaults: { format: 'json' } do
      post '/moderations', to: 'moderations#create'
      post '/users/logout',              to: 'users/sessions#destroy', as: :logout
      get  '/user',                      to: 'users#index'
      post '/users/email_confirmation',  to: 'users/confirmations#create', as: :email_confirmation
      post '/users/resend_confirmation', to: 'users/confirmations#update', as: :resend_confirmation

      get '/current_user',    to: 'current_users#show'
      put '/current_user',    to: 'current_users#update'

      namespace :current_users do
        post '/password_validation', to: 'passwords#show'
      end

      get '/casters/follows', to: 'casters#index'
      get '/casters',         to: 'casters#show'

      namespace :casters do
        resources :likes, except: %i[show new edit], path: '/:caster_id/likes'
        resources :sitemap_ids, only: :index
        post   '/:caster_id/follows', to: 'follows#create'
        delete '/follows/:id',        to: 'follows#destroy'

        post   '/:caster_id/hides',   to: 'hides#create'
        delete '/hides/:id',          to: 'hides#destroy'

        get  '/handles/validation',      to: 'handles#show'
        get  '/emails/validation',       to: 'emails#show'

        get '/:id/contents', to: 'contents#index'
      end

      get '/casters/:id', to: 'casters#show'

      get '/payment_reports', to: 'payment_reports#index', as: :payment_reports, defaults: { format: 'html' }

      namespace :users do
        resources :payments, only: :index, path: '/:user_id/payments'
        resources :metrics, only: :index, path: '/:user_id/metrics'
        resources :publisher_agreements, only: :create, path: '/:user_id/publisher_agreements'
      end

      post 'promotion_banners/:promotion_banner_id/track_click', to: 'promotion_banners#track_click', as: :track_click
      post 'promotion_banners/:promotion_banner_id/track_load', to: 'promotion_banners#track_load', as: :track_load

      post 'promotion_banners/:id/impression', to: 'promotion_banners#track_impression', as: :track_impression
      get '/promotion_banners/:id/metrics', to: 'promotion_banners#metrics',
                                            as: :promotion_banner_metrics
      get '/promotions', to: 'promotion_banners#show'
      get '/promotions/:promotion_id', to: 'promotion_banners#show'
      get '/event_instances/active_dates', to: 'event_instances/active_dates#index'
      get '/event_instances/sitemap_ids', to: 'event_instances/sitemap_ids#index'

      # deprecated
      post 'events/:id/impressions', to: 'metrics/contents/impressions#create'

      resources 'comments', only: %i[index create]
      post '/comments/unsubscribe_from_alerts', to: 'comments#unsubscribe_webhook'
      get '/venues', to: 'business_locations#index', as: :venues
      get '/venue_locations', to: 'business_locations#index', as: :venue_locations,
                              defaults: { autocomplete: true, max_results: 5 }

      get '/locations/locate', to: 'locations/finds#show'
      resources :locations, only: %i[index show]

      get '/feed', to: 'contents#index'

      get '/contents/sitemap_ids', to: 'contents/sitemap_ids#index'
      resources :contents, only: %i[show create update destroy] do
        post '/notifications', to: 'contents/notifications#create'
      end
      get '/contents/:content_id/similar_content', to: 'contents/similar_contents#index'
      get '/contents/:content_id/metrics', to: 'contents/metrics#index'
      # specifying path here to avoid deprecating the frontend even though we've changed
      # the modeling
      namespace :contents do
        get '/:content_id/promotions', to: 'promotions#index'
        post '/:content_id/promotions', to: 'promotions#create'
      end  

      get '/organizations/sitemap_ids', to: 'organizations/sitemap_ids#index'

      # deprecated
      post '/news/:id/impressions', to: 'metrics/contents/impressions#create'

      
      resources 'images', only: %i[create update destroy]

      delete '/content_locations/:id', to: 'content_locations#destroy'

      post '/emails', to: 'emails#create'
      get '/subscriptions', to: 'subscriptions#index'
      get '/subscriptions/:key', to: 'subscriptions#show'
      post '/subscriptions', to: 'subscriptions#create'
      patch'/subscriptions/:key', to: 'subscriptions#update'
      patch '/subscriptions/:key/confirm', to: 'subscriptions#confirm'
      delete 'subscriptions/:key', to: 'subscriptions#destroy'
      delete 'subscriptions/:listserv_id/:email', to: 'subscriptions#destroy'

      get '/digests', to: 'digests#index'
      get '/digests/:id', to: 'digests#show'
      get '/features', to: 'features#index'
      get '/promotion_coupons/:id', to: 'promotion_banners#show_promotion_coupon'
      post '/promotion_coupons/:id/request_email', to: 'promotion_banners#create_promotion_coupon_email'

      post '/metrics/contents/:id/impressions', to: 'metrics/contents/impressions#create'
      resources :content_permissions, only: :index

      post '/metrics/profiles/:id', to: 'metrics/profiles#create'

      resources :mailchimp_webhooks, only: %i[index create]
      resources :rewrites, only: :index
    end
  end
end

app/controllers/api/v3/casters/contents_controller.rb
# frozen_string_literal: true

module Api
  module V3
    class Casters::ContentsController < ApiController

      def index
        if params[:commented] == 'true'
          search_opts = ContentSearch.comment_query(
            params: params,
            current_user: current_user
          )
        elsif params[:caster_feed] == 'true'
          search_opts = ContentSearch.caster_follows_query(
            params: params.merge(caster: true),
            current_user: current_user
          )
        else
          search_opts = ContentSearch.caster_query(
            params: params.merge(caster: true)
          )
        end

        @contents = Content.search(query, search_opts)

        @feed_items = @contents.map do |content|
          FeedItem.new(content)
        end

        render json: FeedContentVanillaSerializer.call(@feed_items).merge(
          meta: {
            total: @contents.total_entries,
            total_pages: total_pages
          }
        )
      end

      private

      def query
        params[:query].present? ? params[:query] : '*'
      end

      def total_pages
        @contents.present? ? (@contents.total_entries / per_page.to_f).ceil : 0
      end

      def per_page
        params[:per_page] || 20
      end
    end
  end
end

app/controllers/api/v3/contents/metrics_controller.rb
module Api
  module V3
    class Contents::MetricsController < ApiController
      before_action :check_logged_in!

      def index
        @content = Content.find(params[:content_id])
        authorize! :manage, @content
        if params[:start_date].present? && params[:end_date].present?
          render json: @content, serializer: ContentMetricsSerializer,
                 context: { start_date: params[:start_date], end_date: params[:end_date] }
        else
          render json: {}, status: :bad_request
        end
      end
    end
  end
end

app/controllers/api/v3/contents/notifications_controller.rb
# frozen_string_literal: true

module Api
  module V3
    class Contents::NotificationsController < ApiController
      def create
        @content = Content.find(params[:content_id])
        authorize! :update, @content
        if @content.mc_campaign_id.nil?
          schedule_email_notification
          render json: {}, status: :ok
        else
          render json: {}, status: :bad_request
        end
      end

      private

      def schedule_email_notification
        BackgroundJob.perform_later('Outreach::SendCasterPostNotification',
                                    'call',
                                    @content)
      end
    end
  end
end

app/controllers/api/v3/contents/promotions_controller.rb
# frozen_string_literal: true

module Api
  module V3
    class Contents::PromotionsController < ApiController
      before_action :check_logged_in!

      def index
        content = Content.find(params[:content_id])
        authorize! :manage, content
        if content.promotions.present?
          render json: content.promotions.shares
        else
          render json: []
        end
      end

      def create
        content = Content.find(params[:content_id])
        authorize! :manage, content
        @promotion = content.promotions.build(promotion_params)
        if @promotion.save
          render json: @promotion, status: :created
        else
          render json: @promotion.errors, status: :unprocessable_entity
        end
      end

      private

      def promotion_params
        params.require(:promotion).permit(
          :created_by,
          :share_platform
        ).tap do |p|
          p[:created_by] = current_user if p[:created_by].present?
        end
      end
    end
  end
end

app/controllers/api/v3/contents/similar_contents_controller.rb
module Api
  module V3
    class Contents::SimilarContentsController < ApiController

      def index
        expires_in 1.minutes, public: true
        @content = Content.find(params[:content_id])

        @similar_content = @content.similar_content(4)

        render json: @similar_content,
          each_serializer: HashieMashes::ContentSerializer,
          root: 'similar_content'
      end
    end
  end
end

app/controllers/api/v3/contents/sitemap_ids_controller.rb
module Api
  module V3
    class Contents::SitemapIdsController < ApiController

      def index
        types = (params[:type] || 'news,market,talk').split(/,\s*/).map do |type|
          if type == 'talk'
            'talk_of_the_town'
          else
            type
          end
        end

        content_ids = Content.not_deleted
                             .not_removed
                             .where('pubdate <= ?', Time.zone.now)
                             .only_categories(types)
                             .order('pubdate DESC')
                             .limit(50_000)
                             .pluck(:id)

        render json: { content_ids: content_ids }
      end
    end
  end
end

app/controllers/api/v3/metrics/contents/impressions_controller.rb
# frozen_string_literal: true

module Api
  module V3
    class Metrics::Contents::ImpressionsController < ApiController
      def create
        @content = Content.not_deleted.find params[:id]

        unless analytics_blocked?
          RecordContentMetric.call(@content, content_metric_params)
        end

        render json: {}, status: :accepted
      end

      private

      def content_metric_params
        data = {
          event_type: 'impression',
          current_date: Date.current.to_s,
          user_id: current_user.try(:id),
          user_agent: request.user_agent,
          user_ip: request.remote_ip,
          client_id: params[:client_id]
        }

        if params[:location_id].present?
          location = Location.find_by_slug_or_id(params[:location_id])
          data[:location_id] = location.try(:id)
          data[:location_confirmed] = ['1', 1, 'true', true].include?(params[:location_confirmed])
        end

        data
      end
    end
  end
end

app/controllers/contents/facebook_scrapings_controller.rb
# frozen_string_literal: true

class Contents::FacebookScrapingsController < ApplicationController
  def create
    @content = Content.find(params[:content_id])
    BackgroundJob.perform_later('FacebookService', 'rescrape_url', @content)
    flash[:notice] = "Content with ID: #{@content.id} has been rescraped"
    redirect_to contents_path
  end
end

app/controllers/contents/removals_controller.rb
# frozen_string_literal: true

class Contents::RemovalsController < ApplicationController
  def create
    @content = Content.find(params[:content_id])
    @content.update_attribute(:removed, true)
    notify_content_owner
    rescrape
    redirect_to edit_content_path(@content)
  end

  def destroy
    @content = Content.find(params[:content_id])
    @content.update_attribute(:removed, false)
    rescrape
    redirect_to edit_content_path(@content)
  end

  private

  def rescrape
    BackgroundJob.perform_later('FacebookService', 'rescrape_url', @content)
  end

  def notify_content_owner
    ContentRemovalAlertMailer.content_removal_alert(@content).deliver_later
  end
end

app/helpers/contents_helper.rb
# frozen_string_literal: true

module ContentsHelper
  def search_field_value(key)
    if params[:reset]
      nil
    elsif session[:contents_search].present?
      session[:contents_search][key]
    elsif params[:q].present?
      params[:q][key]
    end
  end

  def remove_list_from_title(title)
    title.gsub(/\[.*\]/, '') if title.present?
  end

  # confirms that a piece of content has authors, authoremail,
  # and title populated -- returns false if not
  def can_be_listserv_promoted(content)
    content.authors.present? && content.authoremail.present? && content.title.present?
  end

  def ux2_content_path(content)
    content.channel_type == 'Event' ? "/#{content.id}/#{content.channel.next_or_first_instance.id}" : "/#{content.id}"
  end

  def event_feed_content_path(content)
    event = content.channel
    utm_string = "?utm_medium=email&utm_source=rev-pub&utm_content=#{ux2_content_path(content)}"
    "#{ux2_content_path(content)}?eventInstanceId=#{event.next_or_first_instance.id}#{utm_string}"
  end

  def content_url_for_email(content)
    utm_string = "?utm_medium=email&utm_source=rev-pub&utm_content=#{ux2_content_path(content)}"
    url = url_for_consumer_app("#{ux2_content_path(content)}#{utm_string}")

    url
  end

  def comment_alert_url(content)
    utm_string = "?utm_medium=email&utm_source=comment-alert&utm_content=#{ux2_content_path(content)}"
    url = url_for_consumer_app("#{ux2_content_path(content)}#{utm_string}")

    url
  end

  def content_excerpt(content)
    stripped_content = strip_tags(content.raw_content.gsub('<br>', ' '))
    excerpt(stripped_content, stripped_content[0], radius: 105)
  end
end

app/views/contents/destroy.js.haml
$("tr.content-#{@content.id}").remove()

app/views/contents/edit.html.haml
.row-fluid
  .span12.box.bordered-box.blue-border
    - if @content.removed
      .box-header.red-background
        .title
          %i.icon-pencil
          Content Removed! ID #{@content.id} #{@content.title}
    - else
      .box-header.blue-background
        .title
          %i.icon-pencil
          Content ID #{@content.id} #{@content.title}
    .box-content
      = render partial: "contents/partials/form"

app/views/contents/index.html.haml
.row-fluid
  .span12.box.bordered-box.blue-border
    .box-header.blue-background
      .title
        %i.icon-search
        Find Contents
      .actions
        %a.btn.box-remove.btn-mini.btn-link{ href: "#" }
          %i.icon-remove
        %a.btn.box-collapse.btn-mini.btn-link{ href: "#" }
          %i
    .box-content
      = search_form_for @search, url: contents_path do |f|
        .controls.controls-row
          .field.span2
            = f.label :id_in, "ID"
            -# format id_in val for display so it matches what's entered
            - if session[:contents_search].present? and session[:contents_search].has_key? :id_in and session[:contents_search][:id_in].present?
              - id_in_val = session[:contents_search][:id_in].join(',')
            - else
              - id_in_val = ""
            = f.text_field :id_in, value: id_in_val, class: "span12"
          .field.span2
            = f.label :organization_id_in, "Organizations"
            = f.collection_select :organization_id_in, Organization.accessible_by(current_ability), 
              :id, :name, {}, { multiple: true, class: "chosen-select span12" }
          .field.span2
            = f.label :location_id_eq, 'Location'
            = f.collection_select :location_id_eq, @locations,
              :id, :name, { prompt: 'Select' }, { class: 'chosen-select span12' }
          .field.span2
            = f.label :pubdate_gteq, "Pubdate From"
            = f.text_field :pubdate_gteq, type: :date, value: search_field_value(:pubdate_gteq), class: "span12"
          .field.span2
            = f.label :pubdate_lteq, "Pubdate To"
            = f.text_field :pubdate_lteq, type: :date, value: search_field_value(:pubdate_lteq), class: "span12"
        .controls.controls-row
          .field.span2
            = f.label :title_cont, "Title"
            = f.text_field :title_cont, class: "span12"
          .field.span2
            = f.label :authors_or_created_by_name_cont, "Authors"
            = f.text_field :authors_or_created_by_name_cont, class: "span12"
          .field.span2
            = f.label :content_category_in, "Category"
            = f.select :content_category_in, Content::CONTENT_CATEGORIES.collect{ |cat| [cat.titlecase, cat] },
              { include_blank: true },
              { multiple: true, class: "chosen-select span12" }
          .field.span2
            = f.label :pubdate_not_null, "Published?"
            = f.select :pubdate_not_null,
              options_for_select([['All', nil],['Published', 'true'],['Unpublished', 'false']], search_field_value(:pubdate_not_null)),
              {}, { class: 'span12' }
        .controls.controls-row
          .field.span2
            = f.label :event_instances_start_date_gteq, "Start Date"
            = f.text_field :event_instances_start_date_gteq, type: :date, value: search_field_value(:event_instances_start_date_gteq), class: "span12"
          .field.span2
            = f.label :event_instances_end_date_lteq, "End Date"
            = f.text_field :event_instances_end_date_lteq, type: :date, value: search_field_value(:event_instances_end_date_lteq), class: "span12"
        .form-actions
          = f.submit "Search", class: "btn btn-primary"
          = f.submit "Reset", name: "reset", class: "btn"
%table.table.table-striped.table-hover.table-condensed#contents_index
  %thead
    %tr
      %th= sort_link(@search, :id, 'Content ID')
      %th Category
      %th= sort_link(@search, :title)
      %th Organization
      %th Authors
      %th= sort_link(@search, :pubdate)
      %th Initial Start Date
      %th
  .span5
    = page_entries_info @contents if @contents.present?
    = paginate @contents, window: 2 if @contents.present?
  %tbody
    - @contents.each_with_index do |c, i|
      %tr{ class: "content-#{c.id}" }
        %td= c.id
        %td= c.content_category.titlecase
        %td
          = link_to c.title, edit_content_path(c)
          - if c.raw_content.present?
            %br
            .index_content
              - stripped = strip_tags(c.sanitized_content.gsub('<',' <')).gsub(/[[:space:]]{2,}/, ' ')
              = stripped.truncate(50).html_safe
        %td
          - if c.organization.present?
            = link_to c.organization.name, edit_organization_path(c.organization)
        %td
          - if c.author_name.present?
            = link_to CGI.unescape_html(c.author_name).truncate(25), contents_path(q: { authors_cont: c.author_name })
        %td= c.pubdate.try(:strftime, "%Y-%m-%d")
        %td
          - if c.channel_type == 'Event'
            = c.channel.event_instances.first.start_date.try(:strftime, '%Y-%m-%d')
        %td.actions
          = link_to "edit", edit_content_path(c), class: "btn btn-mini btn-warning"

app/views/contents/parent_select_options.js.haml
-# note: the numbers in this conditional are one higher than expected because
  we're inserting the [0, nil] pair in the controller.
- if @contents.length == 2
  $("#content_parent_id").html("#{ j options_for_select(@contents, @contents.last[1]) }");
- elsif @contents.length == 1
  $("#content_parent_id").html("#{ j options_for_select(["No content found.", nil], nil) }");
- else
  $("#content_parent_id").html("#{ j options_for_select(@contents, @orig_content.parent_id) }");

app/views/contents/rdf_to_gate.js.haml
alert("content #{@content.id} not found on ontotext");