config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'

  # custom devise routing
  devise_scope :user do
    post '/api/v3/users/sign_in', to: 'sessions#create'
    post '/api/v3/users/sign_up', to: 'registrations#create'
    post '/api/v3/users/oauth', to: 'sessions#oauth'
    post '/api/v3/password_resets', to: 'api/v3/passwords#create'
    put '/api/v3/password_resets', to: 'api/v3/passwords#update'

    post '/api/v3/users/sign_in_with_token', to: 'sessions#sign_in_with_token'
  end

  get '/' => redirect('/admin')

  # /admin/...
  scope '/admin' do
    authenticated :user do
      mount Sidekiq::Web, at: '/sidekiq'
      root to: 'dashboard#index'
    end

    get "/queue-status", to: 'sidekiq_queues#show'

    devise_for :users, controllers: { sessions: 'sessions', registrations: 'registrations' }

    resources :payments, only: :index
    namespace :payments do
      resources :sends, only: :create
      resources :generates, only: %i[new create]
    end
    resources :ad_reports, only: :index
    delete '/payments/:period_start/:period_end/cancel', to: 'payments#destroy', as: :cancel_payments
    resources :payment_recipients

    get '/users/search', to: 'users/search#index', as: :user_search
    resources :users do
      member do
        put :update_subscription
      end
      resources :archivings, only: %i[new create], controller: 'users/archivings'
    end
    post '/users/admin-create', to: 'users#create', as: 'create_user'
    put '/users/:id/admin-update', to: 'users#update', as: 'update_user'

    get '/', to: 'dashboard#index', as: :dashboard
    get '/dashboard/total_sign_ins', to: 'dashboard#total_sign_ins', as: :total_sign_ins
    get 'dashboard/article_clicks', to: 'dashboard#article_clicks', as: :article_clicks
    get 'dashboard/clicks_by_category', to: 'dashboard#clicks_by_category', as: :clicks_by_category
    get 'dashboard/session_duration', to: 'dashboard#session_duration', as: :session_duration

    get 'contents/parent_options', to: 'contents#parent_select_options', as: :parent_select_options
    resources :contents, except: %i[show new create]
    post 'content/removals', to: 'contents/removals#create'
    delete 'content/removals', to: 'contents/removals#destroy'
    post 'content/facebook_scraping', to: 'contents/facebook_scrapings#create'
    resources :campaigns, except: %i[show destroy]
    resources :comments, only: %i[index update destroy]

    resources :images, only: %i[create destroy update]
    resources :organizations, except: [:show] do
      resources :promotions, shallow: true
    end

    resources :locations, except: [:destroy]
    resources :business_locations

    resources :rewrites, except: [:show]

    resources :listservs do
      resources :campaigns, controller: :listserv_campaigns
    end
    resources :subscriptions

    resources :features

    get '/ics/event_instances/:id', to: 'api/v3/event_instances#show', defaults: { format: 'ics' }, as: :event_instances_ics

    get '/sidekiq_wrapper', to: 'sidekiq_wrapper#index'
  end

  # API
  namespace :api do
    namespace :v3, defaults: { format: 'json' } do
      post '/moderations', to: 'moderations#create'
      post '/users/logout',              to: 'users/sessions#destroy', as: :logout
      get  '/user',                      to: 'users#index'
      post '/users/email_confirmation',  to: 'users/confirmations#create', as: :email_confirmation
      post '/users/resend_confirmation', to: 'users/confirmations#update', as: :resend_confirmation

      get '/current_user',    to: 'current_users#show'
      put '/current_user',    to: 'current_users#update'

      namespace :current_users do
        post '/password_validation', to: 'passwords#show'
      end

      get '/casters/follows', to: 'casters#index'
      get '/casters',         to: 'casters#show'

      namespace :casters do
        resources :likes, except: %i[show new edit], path: '/:caster_id/likes'
        resources :sitemap_ids, only: :index
        post   '/:caster_id/follows', to: 'follows#create'
        delete '/follows/:id',        to: 'follows#destroy'

        post   '/:caster_id/hides',   to: 'hides#create'
        delete '/hides/:id',          to: 'hides#destroy'

        get  '/handles/validation',      to: 'handles#show'
        get  '/emails/validation',       to: 'emails#show'

        get '/:id/contents', to: 'contents#index'
      end

      get '/casters/:id', to: 'casters#show'

      get '/payment_reports', to: 'payment_reports#index', as: :payment_reports, defaults: { format: 'html' }

      namespace :users do
        resources :payments, only: :index, path: '/:user_id/payments'
        resources :metrics, only: :index, path: '/:user_id/metrics'
        resources :publisher_agreements, only: :create, path: '/:user_id/publisher_agreements'
      end

      post 'promotion_banners/:promotion_banner_id/track_click', to: 'promotion_banners#track_click', as: :track_click
      post 'promotion_banners/:promotion_banner_id/track_load', to: 'promotion_banners#track_load', as: :track_load

      post 'promotion_banners/:id/impression', to: 'promotion_banners#track_impression', as: :track_impression
      get '/promotion_banners/:id/metrics', to: 'promotion_banners#metrics',
                                            as: :promotion_banner_metrics
      get '/promotions', to: 'promotion_banners#show'
      get '/promotions/:promotion_id', to: 'promotion_banners#show'
      get '/event_instances/active_dates', to: 'event_instances/active_dates#index'
      get '/event_instances/sitemap_ids', to: 'event_instances/sitemap_ids#index'

      # deprecated
      post 'events/:id/impressions', to: 'metrics/contents/impressions#create'

      resources 'comments', only: %i[index create]
      post '/comments/unsubscribe_from_alerts', to: 'comments#unsubscribe_webhook'
      get '/venues', to: 'business_locations#index', as: :venues
      get '/venue_locations', to: 'business_locations#index', as: :venue_locations,
                              defaults: { autocomplete: true, max_results: 5 }

      get '/locations/locate', to: 'locations/finds#show'
      resources :locations, only: %i[index show]

      get '/feed', to: 'contents#index'

      get '/contents/sitemap_ids', to: 'contents/sitemap_ids#index'
      resources :contents, only: %i[show create update destroy] do
        post '/notifications', to: 'contents/notifications#create'
      end
      get '/contents/:content_id/similar_content', to: 'contents/similar_contents#index'
      get '/contents/:content_id/metrics', to: 'contents/metrics#index'
      # specifying path here to avoid deprecating the frontend even though we've changed
      # the modeling
      namespace :contents do
        get '/:content_id/promotions', to: 'promotions#index'
        post '/:content_id/promotions', to: 'promotions#create'
      end  

      get '/organizations/sitemap_ids', to: 'organizations/sitemap_ids#index'

      # deprecated
      post '/news/:id/impressions', to: 'metrics/contents/impressions#create'

      
      resources 'images', only: %i[create update destroy]

      delete '/content_locations/:id', to: 'content_locations#destroy'

      post '/emails', to: 'emails#create'
      get '/subscriptions', to: 'subscriptions#index'
      get '/subscriptions/:key', to: 'subscriptions#show'
      post '/subscriptions', to: 'subscriptions#create'
      patch'/subscriptions/:key', to: 'subscriptions#update'
      patch '/subscriptions/:key/confirm', to: 'subscriptions#confirm'
      delete 'subscriptions/:key', to: 'subscriptions#destroy'
      delete 'subscriptions/:listserv_id/:email', to: 'subscriptions#destroy'

      get '/digests', to: 'digests#index'
      get '/digests/:id', to: 'digests#show'
      get '/features', to: 'features#index'
      get '/promotion_coupons/:id', to: 'promotion_banners#show_promotion_coupon'
      post '/promotion_coupons/:id/request_email', to: 'promotion_banners#create_promotion_coupon_email'

      post '/metrics/contents/:id/impressions', to: 'metrics/contents/impressions#create'
      resources :content_permissions, only: :index

      post '/metrics/profiles/:id', to: 'metrics/profiles#create'

      resources :mailchimp_webhooks, only: %i[index create]
      resources :rewrites, only: :index
    end
  end
end

app/controllers/api/v3/business_locations_controller.rb
# frozen_string_literal: true

module Api
  module V3
    class BusinessLocationsController < ApiController
      def index
        expires_in 1.minutes, public: true
        query = params[:query].blank? ? '*' : params[:query]
        opts = {}
        opts[:order] = { _score: :desc, name: :desc }
        opts[:per_page] = params[:max_results] || 1000
        opts[:where] = {}
        if current_user.present?
          opts[:where][:or] = [
            [{ created_by_id: current_user.id }, { status: 'approved' }]
          ]
        else
          opts[:where][:status] = 'approved'
        end

        @venues = BusinessLocation.search query, opts

        if params[:autocomplete]
          # it's been requested we also add a single result for city/state  search...
          cs_query = params[:query]
          # The following two lines search extract the (city,state) pair from the search results,
          # then sets cs to the most frequently occurring (city,state) pair
          cities = BusinessLocation.search(cs_query).map { |c| c.city.strip + ', ' + c.state.strip }
          cs = cities.group_by { |n| n }.values.max_by(&:size)

          # reorganize the responses from the search so the locations that begin with the query
          # string appear first, then follow with whatever is left and params[:max_results] results
          response_data = @venues.map { |v| "#{v.name} #{v.city}, #{v.state}".strip }
          leftmost_matches = response_data.select { |v| v =~ /^#{query}/ }.sort
          response_data = leftmost_matches + (response_data - leftmost_matches)
          response_data = response_data.slice(0..params[:max_results] - 1) if params[:max_results].present?

          # stick in the matched city at the top of the returned data
          response_data.prepend cs.first.to_s if cs.present?
          render json: {
            venue_locations: response_data
          }
        else
          render json: @venues, root: 'venues', arrayserializer: BusinessLocationSerializer
        end
      end
    end
  end
end

app/controllers/business_locations_controller.rb
# frozen_string_literal: true

class BusinessLocationsController < ApplicationController
  load_and_authorize_resource

  def index
    # if posted, save to session
    if params[:reset]
      session[:business_locations_search] = nil
    elsif params[:q].present?
      session[:business_locations_search] = params[:q]
    end

    @search = BusinessLocation.ransack(session[:business_locations_search])

    @business_locations = @search.result(distinct: true).page(params[:page]).per(100)
  end

  def edit
    if request.xhr?
      render partial: 'business_locations/partials/form_js', layout: false
    else
      if @business_location.geocoded?
        @nearbys = @business_location.nearbys(3)
        @nearbys = @business_location.nearbys(1) if @nearbys.count(:all) > 25
        @nearbys = @business_location.nearbys(0.5) if @nearbys.count(:all) > 25
        @nearbys = @business_location.nearbys(0.25) if @nearbys.count(:all) > 25
        @events_per_venue = [{}]
        @nearbys.each do |v|
          @events_per_venue[v.id] = v.events.count
        end
      end
      @events = @business_location.events
      render 'edit'
    end
  end

  def new
    if params.key? :organization_id
      @business_location.organization = Organization.find params[:organization_id]
    end
    if request.xhr?
      render partial: 'business_locations/partials/form_js', layout: false
    else
      render 'new'
    end
  end

  def create
    @business_location.created_by = current_user
    @business_location.status = :approved if request.xhr?
    if @business_location.save
      respond_to do |format|
        format.js
        format.html { redirect_to business_locations_path }
      end
    else
      respond_to do |format|
        format.js { render json: @business_location.errors }
        format.html { render 'new' }
      end
    end
  end

  def update
    @business_location.updated_by = current_user
    if @business_location.update_attributes(business_location_params)
      respond_to do |format|
        format.js
        format.html { redirect_to business_locations_path }
      end
    else
      respond_to do |format|
        format.js { render json: @business_location.errors }
        format.html { render 'edit' }
      end
    end
  end

  def destroy
    # don't allow destroy if it'd leave orphaned records
    if @business_location.events.present?
      flash[:notice] = 'Could not destroy record with associated events'
      respond_to do |format|
        format.html { redirect_to business_locations_path }
      end
    else
      @business_location.destroy
      respond_to do |format|
        format.html { redirect_to business_locations_path }
        format.js
      end
    end
  end

  private

  def business_location_params
    params.require(:business_location).permit(:name,
                                              :locate_include_name,
                                              :address,
                                              :city,
                                              :state,
                                              :zip,
                                              :venue_url,
                                              :email,
                                              :phone,
                                              :status,
                                              :organization_id,
                                              hours: []).tap do |attrs|
      if attrs[:hours].respond_to?(:[])
        attrs[:hours].reject!(&:blank?)
      elsif !attrs.key? :hours # deal with removing all hours entries
        attrs[:hours] = []
      end
    end
  end
end

app/views/business_locations/create.js.haml
/ if we are on the organizations page, take the following two actions
if ($("#business_locations_list").length > 0) {
$("tbody#business_locations_list").append("#{ j render 'business_locations/partials/row', business_location: @business_location }");
$("#business_locations_table").dataTable().fnAddTr($("tr.business-location-#{@business_location.id}")[0]);
}

/ fill in hidden field if organization doesn't exist yet
if ($("#organization_business_location_ids").length > 0) {
old_val = $("#organization_business_location_ids").val();
if (old_val.length > 0) { new_val = old_val + ",#{@business_location.id}"; }
else { new_val = "#{@business_location.id}"; }
$("#organization_business_location_ids").val(new_val);
}

/ otherwise, if a business_location select box is on the page, we need to add the new one to it.
if ($("#event_venue_id").length > 0) {
$("#event_venue_id").append("#{ j options_from_collection_for_select([@business_location], 'id', 'select_option_label') }");
$("#event_venue_id").val("#{@business_location.id}").trigger("chosen:updated");
}

app/views/business_locations/destroy.html.haml
%h1 BusinessLocations#destroy
%p Find me in app/views/business_locations/destroy.html.haml

app/views/business_locations/destroy.js.haml
$("#business_locations_table").dataTable().fnDeleteRow($("tr.business-location-#{@business_location.id}")[0]);

app/views/business_locations/edit.html.haml
.row-fluid
  .span12.box.bordered-box.blue-border
    .box-header.blue-background
      .title
        %i.icon-pencil
        Venue ID #{@business_location.id}
    .box-content
      = render partial: 'business_locations/partials/form'

      .row-fluid#nearbys
        = render partial: 'business_locations/partials/nearbys'

      .row_fluid#venue-events
        = render partial: 'business_locations/partials/venue_events'

app/views/business_locations/edit.js.haml
/ logic for event
if ($("#event_venue_id").length > 0) {
/ find option tag for @business_location and update it
$('#event_venue_id option[value="#{@business_location.id}"]').text("#{ @business_location.select_option_label }");
$("#event_venue_id").change();
}

app/views/business_locations/index.html.haml
.row-fluid
  .span12.box.bordered-box.blue-border
    .box-header.blue-background
      .title
        %i.icon-search
        Find Venues
      .actions
        %a.btn.box-remove.btn-mini.btn-link{ href: "#" }
          %i.icon-remove
        %a.btn.box-collapse.btn-mini.btn-link{ href: "#" }
          %i
    .box-content
      = search_form_for @search, url: business_locations_path do |f|
        .controls.controls-row
          .field.span3
            = f.label :name_cont, "Name"
            = f.text_field :name_cont, class: 'span12'
          .field.span3
            = f.label :address_cont, 'Address'
            = f.text_field :address_cont, class: 'span12'
          .field.span3
            = f.label :status_in, 'Status'
            = f.select :status_in, BusinessLocation::STATUS_CATEGORIES, {}, { multiple: true, class: 'chosen-select' }
        .form-actions
          = f.submit "Search", class: "btn btn-primary"
          = f.submit "Reset", name: "reset", class: "btn"
          
%table.table.table-striped.table-bordered.table-condensed.display#business_locations_table
  %thead
    %tr
      %th Name
      %th Address
      %th Status
      %th ID
      %th
  .span5
    = page_entries_info @business_locations if @business_locations.present?
    = paginate @business_locations, window: 2 if @business_locations.present?
  %tbody
    - @business_locations.each do |venue|
      %tr{ class: "venue-#{venue.id}" }
        %td= venue.name
        %td= venue.full_address
        %td= venue.status
        %td= venue.id
        %td.actions
          = link_to "edit", edit_business_location_path(venue), class: "btn btn-mini btn-warning"

app/views/business_locations/new.html.haml
.row-fluid
  .span12.box.bordered-box.blue-border
    .box-header.blue-background
      .title
        %i.icon-plus
        Add a Venue
    .box-content
      = simple_form_for @business_location do |f|
        = render partial: 'business_locations/partials/form_fields', locals: { f: f, include_status: true }

app/views/business_locations/update.js.haml
/ logic for organizations page
if ($("#business_locations_table").length > 0) {
$("#business_locations_table").dataTable().fnUpdate(#{ render 'business_locations/partials/datatable_row', business_location: @business_location},$("tr.business-location-#{@business_location.id}")[0]);
}

/ logic for event
if ($("#event_venue_id").length > 0) {
/ find option tag for @business_location and update it
$('#event_venue_id option[value="#{@business_location.id}"]').text("#{ @business_location.select_option_label }");
$("#event_venue_id").change();
}