config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'

  # custom devise routing
  devise_scope :user do
    post '/api/v3/users/sign_in', to: 'sessions#create'
    post '/api/v3/users/sign_up', to: 'registrations#create'
    post '/api/v3/users/oauth', to: 'sessions#oauth'
    post '/api/v3/password_resets', to: 'api/v3/passwords#create'
    put '/api/v3/password_resets', to: 'api/v3/passwords#update'

    post '/api/v3/users/sign_in_with_token', to: 'sessions#sign_in_with_token'
  end

  get '/' => redirect('/admin')

  # /admin/...
  scope '/admin' do
    authenticated :user do
      mount Sidekiq::Web, at: '/sidekiq'
      root to: 'dashboard#index'
    end

    get "/queue-status", to: 'sidekiq_queues#show'

    devise_for :users, controllers: { sessions: 'sessions', registrations: 'registrations' }

    resources :payments, only: :index
    namespace :payments do
      resources :sends, only: :create
      resources :generates, only: %i[new create]
    end
    resources :ad_reports, only: :index
    delete '/payments/:period_start/:period_end/cancel', to: 'payments#destroy', as: :cancel_payments
    resources :payment_recipients

    get '/users/search', to: 'users/search#index', as: :user_search
    resources :users do
      member do
        put :update_subscription
      end
      resources :archivings, only: %i[new create], controller: 'users/archivings'
    end
    post '/users/admin-create', to: 'users#create', as: 'create_user'
    put '/users/:id/admin-update', to: 'users#update', as: 'update_user'

    get '/', to: 'dashboard#index', as: :dashboard
    get '/dashboard/total_sign_ins', to: 'dashboard#total_sign_ins', as: :total_sign_ins
    get 'dashboard/article_clicks', to: 'dashboard#article_clicks', as: :article_clicks
    get 'dashboard/clicks_by_category', to: 'dashboard#clicks_by_category', as: :clicks_by_category
    get 'dashboard/session_duration', to: 'dashboard#session_duration', as: :session_duration

    get 'contents/parent_options', to: 'contents#parent_select_options', as: :parent_select_options
    resources :contents, except: %i[show new create]
    post 'content/removals', to: 'contents/removals#create'
    delete 'content/removals', to: 'contents/removals#destroy'
    post 'content/facebook_scraping', to: 'contents/facebook_scrapings#create'
    resources :campaigns, except: %i[show destroy]
    resources :comments, only: %i[index update destroy]

    resources :images, only: %i[create destroy update]
    resources :organizations, except: [:show] do
      resources :promotions, shallow: true
    end

    resources :locations, except: [:destroy]
    resources :business_locations

    resources :rewrites, except: [:show]

    resources :listservs do
      resources :campaigns, controller: :listserv_campaigns
    end
    resources :subscriptions

    resources :features

    get '/ics/event_instances/:id', to: 'api/v3/event_instances#show', defaults: { format: 'ics' }, as: :event_instances_ics

    get '/sidekiq_wrapper', to: 'sidekiq_wrapper#index'
  end

  # API
  namespace :api do
    namespace :v3, defaults: { format: 'json' } do
      post '/moderations', to: 'moderations#create'
      post '/users/logout',              to: 'users/sessions#destroy', as: :logout
      get  '/user',                      to: 'users#index'
      post '/users/email_confirmation',  to: 'users/confirmations#create', as: :email_confirmation
      post '/users/resend_confirmation', to: 'users/confirmations#update', as: :resend_confirmation

      get '/current_user',    to: 'current_users#show'
      put '/current_user',    to: 'current_users#update'

      namespace :current_users do
        post '/password_validation', to: 'passwords#show'
      end

      get '/casters/follows', to: 'casters#index'
      get '/casters',         to: 'casters#show'

      namespace :casters do
        resources :likes, except: %i[show new edit], path: '/:caster_id/likes'
        resources :sitemap_ids, only: :index
        post   '/:caster_id/follows', to: 'follows#create'
        delete '/follows/:id',        to: 'follows#destroy'

        post   '/:caster_id/hides',   to: 'hides#create'
        delete '/hides/:id',          to: 'hides#destroy'

        get  '/handles/validation',      to: 'handles#show'
        get  '/emails/validation',       to: 'emails#show'

        get '/:id/contents', to: 'contents#index'
      end

      get '/casters/:id', to: 'casters#show'

      get '/payment_reports', to: 'payment_reports#index', as: :payment_reports, defaults: { format: 'html' }

      namespace :users do
        resources :payments, only: :index, path: '/:user_id/payments'
        resources :metrics, only: :index, path: '/:user_id/metrics'
        resources :publisher_agreements, only: :create, path: '/:user_id/publisher_agreements'
      end

      post 'promotion_banners/:promotion_banner_id/track_click', to: 'promotion_banners#track_click', as: :track_click
      post 'promotion_banners/:promotion_banner_id/track_load', to: 'promotion_banners#track_load', as: :track_load

      post 'promotion_banners/:id/impression', to: 'promotion_banners#track_impression', as: :track_impression
      get '/promotion_banners/:id/metrics', to: 'promotion_banners#metrics',
                                            as: :promotion_banner_metrics
      get '/promotions', to: 'promotion_banners#show'
      get '/promotions/:promotion_id', to: 'promotion_banners#show'
      get '/event_instances/active_dates', to: 'event_instances/active_dates#index'
      get '/event_instances/sitemap_ids', to: 'event_instances/sitemap_ids#index'

      # deprecated
      post 'events/:id/impressions', to: 'metrics/contents/impressions#create'

      resources 'comments', only: %i[index create]
      post '/comments/unsubscribe_from_alerts', to: 'comments#unsubscribe_webhook'
      get '/venues', to: 'business_locations#index', as: :venues
      get '/venue_locations', to: 'business_locations#index', as: :venue_locations,
                              defaults: { autocomplete: true, max_results: 5 }

      get '/locations/locate', to: 'locations/finds#show'
      resources :locations, only: %i[index show]

      get '/feed', to: 'contents#index'

      get '/contents/sitemap_ids', to: 'contents/sitemap_ids#index'
      resources :contents, only: %i[show create update destroy] do
        post '/notifications', to: 'contents/notifications#create'
      end
      get '/contents/:content_id/similar_content', to: 'contents/similar_contents#index'
      get '/contents/:content_id/metrics', to: 'contents/metrics#index'
      # specifying path here to avoid deprecating the frontend even though we've changed
      # the modeling
      namespace :contents do
        get '/:content_id/promotions', to: 'promotions#index'
        post '/:content_id/promotions', to: 'promotions#create'
      end  

      get '/organizations/sitemap_ids', to: 'organizations/sitemap_ids#index'

      # deprecated
      post '/news/:id/impressions', to: 'metrics/contents/impressions#create'

      
      resources 'images', only: %i[create update destroy]

      delete '/content_locations/:id', to: 'content_locations#destroy'

      post '/emails', to: 'emails#create'
      get '/subscriptions', to: 'subscriptions#index'
      get '/subscriptions/:key', to: 'subscriptions#show'
      post '/subscriptions', to: 'subscriptions#create'
      patch'/subscriptions/:key', to: 'subscriptions#update'
      patch '/subscriptions/:key/confirm', to: 'subscriptions#confirm'
      delete 'subscriptions/:key', to: 'subscriptions#destroy'
      delete 'subscriptions/:listserv_id/:email', to: 'subscriptions#destroy'

      get '/digests', to: 'digests#index'
      get '/digests/:id', to: 'digests#show'
      get '/features', to: 'features#index'
      get '/promotion_coupons/:id', to: 'promotion_banners#show_promotion_coupon'
      post '/promotion_coupons/:id/request_email', to: 'promotion_banners#create_promotion_coupon_email'

      post '/metrics/contents/:id/impressions', to: 'metrics/contents/impressions#create'
      resources :content_permissions, only: :index

      post '/metrics/profiles/:id', to: 'metrics/profiles#create'

      resources :mailchimp_webhooks, only: %i[index create]
      resources :rewrites, only: :index
    end
  end
end

app/models/listserv.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: listservs
#
#  id                          :bigint(8)        not null, primary key
#  name                        :string(255)
#  import_name                 :string(255)
#  active                      :boolean
#  created_at                  :datetime         not null
#  updated_at                  :datetime         not null
#  digest_send_time            :time
#  unsubscribe_email           :string
#  post_email                  :string
#  subscribe_email             :string
#  mc_list_id                  :string
#  mc_group_name               :string
#  send_digest                 :boolean          default(FALSE)
#  last_digest_send_time       :datetime
#  last_digest_generation_time :datetime
#  digest_header               :text
#  digest_footer               :text
#  digest_reply_to             :string
#  timezone                    :string           default("Eastern Time (US & Canada)")
#  digest_description          :text
#  digest_send_day             :string
#  template                    :string
#  sponsored_by                :string
#  display_subscribe           :boolean          default(FALSE)
#  digest_subject              :string
#  digest_preheader            :string
#  sender_name                 :string
#  promotion_ids               :integer          default([]), is an Array
#  admin_email                 :string
#  forwarding_email            :string
#  forward_for_processing      :boolean          default(FALSE)
#  post_threshold              :integer          default(0)
#

class Listserv < ActiveRecord::Base
  include ListservSupport
  include HasPromotionForBanner

  has_many :promotion_listservs
  has_and_belongs_to_many :locations
  has_many :subscriptions
  has_many :campaigns

  validates_uniqueness_of :unsubscribe_email,
                          :subscribe_email, :post_email, allow_blank: true

  validates :digest_reply_to, presence: true, if: :send_digest?
  validates :digest_send_time, presence: true, if: :send_digest?
  validates :forwarding_email, presence: true, if: :forward_for_processing?

  validate :mc_group_name_required, if: :mc_list_id?

  validate :valid_template_name

  scope :active, -> { where(active: true) }

  DIGEST_TEMPLATES = Dir.entries('app/views/listserv_digest_mailer/').map { |file| file.split('.').first }.compact

  def mc_group_name=(n)
    write_attribute :mc_group_name, (n.nil? ? n : n.strip)
  end

  def promotions_list=(list)
    write_attribute(:promotion_ids, list.split(/[,\s]+/))
  end

  def promotions_list
    promotion_ids.join(', ')
  end

  def active_subscriber_count
    subscriptions.active.count
  end

  def is_managed_list?
    subscribe_email.present? || post_email.present? || unsubscribe_email.present?
  end

  def mc_sync?
    mc_list_id? && mc_group_name?
  end

  def valid_template_name
    if template? && DIGEST_TEMPLATES.exclude?(template)
      errors.add(:template, 'Please enter a valid template')
    end
  end

  def next_digest_send_time
    if digest_send_time? && !digest_send_day?
      tm = parse_digest_send_time
      tm.future? ? tm : tm.tomorrow
    elsif digest_send_time? && digest_send_day?
      tm = digest_send_time.strftime('%H:%M')
      Chronic.parse("#{digest_send_day} #{tm}")
    end
  end

  def banner_ads
    promotions.map(&:promotable) if promotions.any?
  end

  def self.digest_days
    %w[
      Sunday
      Monday
      Tuesday
      Wednesday
      Thursday
      Friday
      Saturday
    ]
  end

  def digest_contents(location_ids)
    content_ids = Content
      .select('contents.id')
      .joins('INNER JOIN users ON users.id = contents.created_by_id')
      .joins('INNER JOIN locations ON contents.location_id = locations.id')
      .where('pubdate IS NOT NULL AND pubdate < NOW() AND pubdate >= ?', digest_date_bound)
      .where(contents: { content_category: 'news' })
      .where(contents: { location_id: location_ids })
      .where(contents: { removed: false })
      .where('contents.id IN (
        SELECT id
        FROM contents
        WHERE created_by_id = users.id AND pubdate >= ? AND pubdate < NOW() AND pubdate IS NOT NULL
        ORDER BY view_count DESC LIMIT 3
      )', digest_date_bound)
    Content.where(id: content_ids).order(view_count: :desc).limit(limit)
  end

  def digest_date_bound
    # weekly
    if digest_send_day?
      1.week.ago
    else # daily
      30.hours.ago
    end
  end

  def limit
    digest_send_day? ? 10 : 8
  end

  def promotions
    if promotion_ids.any?
      Promotion.where(id: promotion_ids).sort_by { |p| promotion_ids.index(p.id) }
    else
      []
    end
  end

  def parse_digest_send_time
    Time.zone.parse(digest_send_time.strftime('%H:%M'))
  end

  def mc_group_name_required
    if mc_list_id?
      unless mc_group_name?
        errors.add(:mc_group_name, 'required when mc_list_id present')
      end
    end
  end

  def locations
    Location.joins(users: [:subscriptions]).where(subscriptions: { listserv_id: id }).distinct
  end
end

app/controllers/listservs_controller.rb
# frozen_string_literal: true

class ListservsController < ApplicationController
  before_action :set_listserv, only: %i[show edit update destroy]

  def index
    # if posted, save to session
    if params[:reset]
      session[:listservs_search] = nil
    elsif params[:q].present?
      session[:listservs_search] = params[:q]
    end
    unless session[:listservs_search].present?
      session[:listservs_search] = { active_true: true }
    end
    @search = Listserv.ransack(session[:listservs_search])
    @listservs = @search.result(distinct: true)
  end

  def show; end

  def new
    @listserv = Listserv.new
  end

  def edit
    @digest_days = Listserv.digest_days
  end

  def create
    @listserv = Listserv.new(listserv_params)

    if @listserv.save
      redirect_to listservs_url, notice: 'Listserv was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @listserv.update(listserv_params)
      redirect_to listservs_url, notice: 'Listserv was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @listserv.destroy
    redirect_to listservs_url
  end

  private

  def set_listserv
    @listserv = Listserv.find(params[:id])
  end

  def listserv_params
    params.require(:listserv).permit(
      :active,
      :import_name,
      :name,
      :subscribe_email,
      :unsubscribe_email,
      :post_email,
      :digest_send_time,
      :mc_list_id,
      :mc_group_name,
      :digest_header,
      :digest_footer,
      :send_digest,
      :digest_reply_to,
      :timezone,
      :digest_description,
      :digest_send_day,
      :template,
      :sponsored_by,
      :display_subscribe,
      :digest_preheader,
      :digest_subject,
      :sender_name,
      :admin_email,
      :promotions_list,
      :forwarding_email,
      :forward_for_processing,
      :post_threshold,
      promotion_ids: []
    )
  end
end

app/views/listservs/_form.html.haml
= simple_form_for @listserv, html: {class: 'form form-horizontal'} do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :sender_name
    = f.input :digest_description
    = f.input :import_name
    = f.input :forwarding_email, hint: "Email address to forward all received posting emails for archiving"
    = f.input :forward_for_processing, as: :boolean
    = f.input :post_threshold, hint: "Minimum number of posts required before digest will send."
    = f.input :active, as: :boolean
    .form-actions
      = f.button :submit, class: 'btn btn-success'
    %fieldset
      %legend Subtext Managed Listserv
      = f.input :subscribe_email
      = f.input :unsubscribe_email
      = f.input :post_email
      = f.input :mc_list_id
      = f.input :mc_group_name
      = f.input :admin_email
      .form-actions
        = f.button :submit, class: 'btn btn-success'
      %fieldset
        %legend Digest Settings
        = f.input :send_digest
        = f.input :digest_send_time, prompt: true, ampm: true, hint: "In your timezone (#{Time.zone.name})"
        = f.input :timezone, as: :time_zone, priority: /US/, hint: "The timezone digest receivers would typically be in."
        = f.input :digest_send_day, collection: Listserv.digest_days, hint: "If this is a weekely digest, select the day of the week to send.  Leave blank if daily"
        = f.input :digest_reply_to
        = f.input :digest_subject
        = f.input :digest_preheader
        = f.input :digest_header, as: :summernote
        = f.input :digest_footer, as: :summernote
        = f.input :template, collection: Listserv::DIGEST_TEMPLATES, include_blank: false
        = f.input :sponsored_by, hint: "Ex: 'Sponsored by Monsanto'"
        = f.input :promotion_ids do
          = f.input_field :promotions_list
        = f.input :display_subscribe, label: "Subscription option on HereCast registration and user account"

        .form-actions
          = f.button :submit, class: 'btn btn-success'

      - if @listserv.persisted?
        %fieldset#campaigns
          %legend
            Campaigns
            %button.btn.new-campaign{type: 'button', data: {template: ((render("listserv_campaigns/form", campaign: Campaign.new(listserv: f.object))))}}
              %i.glyphicon.glyphicon-plus
              New

          %table.table.table-striped
            %thead
              %tr
                %th Communities
                %th Sponsored By
                %th Promotion
                %th
            %tbody
              - @listserv.campaigns.each do |campaign|
                = render 'listserv_campaigns/row', campaign: campaign

          %script#campaignModal{type: 'text/html'}
            .modal.fade
              .modal-dialog
                .modal-content
                  .modal-header
                    %button.close{type: 'button', "data-dismiss"=>"modal"}
                      &times;
                    %h4.modal-title Campaign
                  .modal-body
                  .modal-footer
                    %button.btn.btn-primary{type: 'button'} Save Changes

          :javascript
            jQuery(function($){
              var template = $('#campaignModal').html();
              var $campaigns = $('#campaigns');

              function buildModal($btn) {
                var $modal = $(template).appendTo($('body'));
                $modal.find('.modal-body').append($btn.data('template'));

                $modal.modal({
                  show: false
                }).on('hidden.bs.modal', function() {
                  $modal.remove();
                }).on('click', 'button.btn-primary', function() {
                  $modal.find('form').submit();
                }).on('ajax:success', function() {
                  $modal.modal('hide');
                });
                return $modal;
              }

              $campaigns.on('click', 'button.new-campaign', function() {
                var $modal = buildModal($(this));
                $modal.modal('show');
              });

              $campaigns.on('click', 'button.edit-campaign', function() {
                var $modal = buildModal($(this));
                $modal.find('#campaign_community_ids').val()
                $modal.modal('show');
              });

            });

app/views/listservs/edit.html.haml
%div.span12.box.bordered-box.blue-border
  %div.box-header.blue-background
    .title
      %i.icon-pencil
      Listserv ID #{@listserv.id}
  %div.box-content
    = render 'form'
    = link_to 'Back', listservs_path

app/views/listservs/index.html.haml
.row-fluid
  .span12.box.bordered-box.blue-border
    .box-header.blue-background
      .title
        %i.icon-search
        Digests
    .box-content
      = search_form_for @search, url: listservs_path do |f|
        .controls.controls-row
          .field.span2
            = f.label :active_true, "Active"
            = f.check_box :active_true
        .form-actions
          = f.submit "Search", class: "btn btn-primary"
          = f.submit "Reset", name: "reset", class: "btn"

%table.table.table-striped.table-bordered.table-condensed
  %caption Displaying #{@listservs.count} listservs
  %thead
    %tr
      %th ID
      %th Name
      %th Digest Time
      %th Digest Day
      %th Subscribers
      %th

  %tbody
    - @listservs.each do |ls|
      %tr{ class: "listserv-#{ls.id}" }
        %td= ls.id
        %td= link_to ls.name, edit_listserv_path(ls)
        %td= ls.digest_send_time.strftime('%H:%M') if ls.digest_send_time?
        %td= ls.digest_send_day
        %td= ls.active_subscriber_count
        %td
          = link_to "Edit", edit_listserv_path(ls), class: 'btn btn-mini'

app/views/listservs/new.html.haml
%div.span12.box.bordered-box.blue-border
  %div.box-header.blue-background
    .title
      %i.icon-pencil
      New Listserv
  %div.box-content
    = render 'form'
    = link_to 'Back', listservs_path

app/views/listservs/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_listserv_path(@listserv)
\|
= link_to 'Back', listservs_path